name: Automation

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
      pod update  
      xcodebuild -scheme iOS  build
