name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Pod Update
      run: pod update  
    - name: Build
      run:  xcodebuild -project MVI.xcodeproj -alltargets -configuration Debug
