name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: 
        pod update
        swift build -v
    - name: Run tests
      run: 
        pod update
        swift test -v
